### ISSUE TITLE
Error: Cannot find module 'vscode-languageserver-protocol'

### ISSUE THREAD

**Issue by oblitum** [josa42/coc-docker#40]
After `:CocInstall coc-docker`, closing NeoVim and then opening a Dockerfile I get:

```
[coc.nvim] Error on load extension coc-docker from /home/francisco/.config/coc/extensions/node_modules/coc-docker/lib/extension.js: Error: Cannot find module 'vscode-languageserver-protocol'
Require stack:
- /home/francisco/.config/coc/extensions/node_modules/coc-docker/lib/dockerCompose/dockerComposeCompletionItemProvider.js
- /home/francisco/.config/coc/extensions/node_modules/coc-docker/lib/extension.js
- /home/francisco/.config/coc/extensions/node_modules/coc-docker/lib/extension.js
```

**Comment by josa42** [comment]
I cannot reproduce this issue.

**Comment by oblitum** [comment]
Just tried it again, completely new machine than the one I used at the time, still same issue.

**Comment by oblitum** [comment]
fwiw, the source code have imports for [vscode-languageserver-protocol](https://github.com/josa42/coc-docker/search?q=%27vscode-languageserver-protocol), but it's not on dependencies or dev deps in `package.json`. Not sure whether it should have been or not.
